audit_header: false
title: "Mastermind Club Blog"
description: The Mastermind of Entrepreneurial Real Estate Agents Who Share Their 7-and-8 Figure Plans and Strategies...So You Too Can Grow Your Business with Ease In a Way That Makes You Happy
show_custom_links: false
custom_links:
  - title: Join Our Team
    url: /join-our-team/
  - title: Events
    url: #
  - title: Free Strategy Call
    url: /contact/
client:
  name:
  title:
  license_number:
  about_markdown: |

  market:
  brand:
  brokerage:
  address:
  phone:
  phone_type:
  phone2:
  phone2_type:
  email:
  url:

sidebar_CTA:
  - CTA_image_path: /img/cta-images/001.png
    CTA_title: "Grow Your Real Estate Business with Ease"
    CTA_text: "A Private Learning Club of Real Estate Agent Teams and Rainmakers"
    CTA_link_text: "Learn More"
    CTA_url: https://www.mastermindclub.us/

# second_sidebar_CTA:
#   - CTA_image_path2: /img/cta-images/002.jpg
#     CTA_title2: "Join Our Team"
#     CTA_text2: "Sell more homes by joining forces with the our dynamic real estate company."
#     CTA_link_text2: "Career Info"
#     CTA_url2: /

lender:
  show_section: false
  header_text: Preferred Lender
  headshot_path: http://fillmurray.com/200/200
  logo_path: /img/logo.png
  logo_path_2:
  name: Bill Murray
  brand: Lender Co.
  phone: 555-555-5555
  email: bill@murray.com
  url: http://eyegoop.com

socials:
  review_sm_icons: false
  facebook_url: https://www.facebook.com/MastermindClub.Us/
  linkedin_url:
  gplus_url:
  youtube_url:
  twitter_url:
  instagram_url:
  pinterest_url:
  zillow_url:
  trulia_url:
  yelp_url:
  podcast_url:

podcast:
  title: '-- MARKET -- Real Estate Podcast with -- CLIENT NAME --'
  categories: Education
  image: /img/podcast.jpg
  subtitle: 'Learn all the tips, tricks and more for buyers and sellers in the -- MARKET -- Area Real Estate Market'
  description: 'If you are looking to buy or sell a home, get all the information and the latest updates, tips, and tricks from -- CLIENT BRAND -- - your professional -- MARKET -- Real Estate Agents.'
  keywords: 'Real Estate for sale, Real Estate agents, top real estate agents, local real estate agents, find a real estate agent, houses for sale in -- MARKET --, home selling tips, home for sale, home buying, home buying process, property finder, property search, property, real estate market, estate agent, realestate, real estate listings, buying a house, homes for sale, mls, home buyer'
  author: '-- CLIENT NAME --'

images:
  client_headshot_path: /img/headshot.jpg
  hero_logo_path: /img/logo.png
  logo_width_number: 40
  hero_text: -- MARKET -- Real Estate Video Blog
  hero_background_hex: '#999'
  hero_image_path: /img/background.jpg
  post_cover: /img/cover.jpg
site_colors:
  brand_color: '#5B1928'
  theme_color: '#000'
  theme_text_color: '#5d9bd3'
  main_body_color: '#ffffff'
  main_body_text_color: '#353535'

navbar_colors:
  border_bottom:

header_shadow:
  h_shadow: 0px
  w_shadow: 2px
  shadow_spread: 7px
  shadow_color: black

buttons:
  button_radius_number: 0
  button_padding_width_number: 10
  button_padding_height_number: 15
  button_border_color: '#ffffff'
  button_background_color: transparent
  button_text_color: '#123456'
  secondary_button_border_color: '#ffffff'
  secondary_button_background_color: 'rgba(0, 0, 0, 0)'
  secondary_button_text_color: '#ffffff'
